version = 0
commit_goodlist = []

[authorization.Velocifyer]
sign_commit = true
sign_tag = true
sign_archive = true
keyring = """
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: 1BA0 FC4B 80E0 F21B 0269  8CEE 634E BF87 40C7 48BE
Comment: Velocifyer <velocifyer@velocifyer.com>

xjMEaCpEhBYJKwYBBAHaRw8BAQdAZBZWSN4ekixMHE7duMBmw/2uteCfmp68D/mx
aYk/dyrNJlZlbG9jaWZ5ZXIgPHZlbG9jaWZ5ZXJAdmVsb2NpZnllci5jb20+wo8E
ExYIADcWIQQboPxLgODyGwJpjO5jTr+HQMdIvgUCaCpEhAUJBaOagAIbAwQLCQgH
BRUICQoLBRYCAwEAAAoJEGNOv4dAx0i+HU8BAJGd99DA1VdBzcYgch16XK7mC78Z
qEwGegVCRerWry8RAQC3MJUOiyQ062Ol/3iNXY6zk2QXaAsV8eUbFKUo1HiwAg==
=fZKV
-----END PGP PUBLIC KEY BLOCK-----
"""
